// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzyasPzcVPed7jJkMWcDIzSP8j9KPYWD4',
    appId: '1:468848246757:web:2d85b0f35e0c3bc243390c',
    messagingSenderId: '468848246757',
    projectId: 'pos-selforder-mvp',
    authDomain: 'pos-selforder-mvp.firebaseapp.com',
    storageBucket: 'pos-selforder-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJyJhuRcc8_NXeZ1eH0fDLhtUyp9gsL8',
    appId: '1:468848246757:android:11b7162eb79b147c43390c',
    messagingSenderId: '468848246757',
    projectId: 'pos-selforder-mvp',
    storageBucket: 'pos-selforder-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClAz0Bg3WGVA7aNdJJIwxHPoi4g2YgPwE',
    appId: '1:468848246757:ios:ac36b043fac500ce43390c',
    messagingSenderId: '468848246757',
    projectId: 'pos-selforder-mvp',
    storageBucket: 'pos-selforder-mvp.firebasestorage.app',
    iosBundleId: 'com.example.restaurantPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClAz0Bg3WGVA7aNdJJIwxHPoi4g2YgPwE',
    appId: '1:468848246757:ios:ac36b043fac500ce43390c',
    messagingSenderId: '468848246757',
    projectId: 'pos-selforder-mvp',
    storageBucket: 'pos-selforder-mvp.firebasestorage.app',
    iosBundleId: 'com.example.restaurantPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzyasPzcVPed7jJkMWcDIzSP8j9KPYWD4',
    appId: '1:468848246757:web:19bbc55fed4142ab43390c',
    messagingSenderId: '468848246757',
    projectId: 'pos-selforder-mvp',
    authDomain: 'pos-selforder-mvp.firebaseapp.com',
    storageBucket: 'pos-selforder-mvp.firebasestorage.app',
  );

}